version: "3.9"

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - ./:/db
    networks:
      network:
        ipv4_address: 10.1.0.2

networks:
  network:
    name: network-mongo
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
